// swift-tools-version: 5.7

// This is the Swift Playgrounds *App Playground* manifest. It is deliberately
// not the same as the repository's Package.swift: Playgrounds builds a single
// module called AppModule, so every source file here is flat and nothing
// imports anything else from the project.
//
// Generated by Tools/make_swiftpm.py — edit the template, not the output.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "PixelRogue",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "PixelRogue",
            targets: ["AppModule"],
            bundleIdentifier: "com.pixelforge.pixelrogue",
            teamIdentifier: "",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            // Landscape is how the game wants to be held — the playfield is
            // wider than it is tall and the thumb controls need the width —
            // but all four are listed because Playgrounds warns otherwise,
            // and the HUD anchors to the corners so portrait still works.
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft,
                .portrait,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            resources: [
                .process("Resources")
            ]
        )
    ]
)
